# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=40)),
                ('caption', models.CharField(max_length=60)),
                ('likes', models.IntegerField(default='none')),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
