# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 06:31
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_auto_20191017_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
