# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0004_auto_20191021_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilepic',
            new_name='profile',
        ),
    ]
