# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_auto_20191021_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
